on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      tag_name:
        description: "リリースのタグ名"
        type: string

jobs:
  identify-what-to-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}

      - run: |
          echo "tagname: ${{ inputs.tag_name }}"
