on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  identify-what-to-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo ${{ github.event.ref }}
