on:
  workflow_dispatch:
  
permissions:
  contents: write
  id-token: write

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: softprops/action-gh-release@v2
        id: create-gh-release
        with:
          prerelease: true
          name: test/tag/20241119
          tag_name: test/tag/20241119
          generate_release_notes: true
      
      - run: echo ${{ steps.create-gh-release.outputs.url }}
