on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "リリースのタグ名"
        type: string
        required: true

jobs:
  prepare-release-object:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.set_outputs.outputs.tag_name }}
      prerelease: ${{ steps.set_outputs.outputs.prerelease }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          ref: ${{ github.event.inputs.tag_name }}

      - name: Handle workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: get_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ inputs.tag_name }}
          prerelease: true

      - name: Set Outputs
        id: set_outputs
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag_name=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
            echo "prerelease=${{ steps.get_release.outputs.prerelease }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
            echo "prerelease=${{ github.event.release.prerelease }}" >> $GITHUB_OUTPUT
          fi

  show-params:
    needs: [prepare-release-object]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "tag_name: ${{ needs.prepare-release-object.outputs.tag_name }}"
          echo "prerelease: ${{ needs.prepare-release-object.outputs.prerelease }}"
