on:
  release:
    types: [deleted]
    
jobs:
  show-diffs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - uses: dorny/paths-filter@v3
        id: paths-filter
        with:
          filters: |
            test:
              - "test/**"
