on:
  release:
    types: [released]

jobs:
  show-release-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "name: ${{ github.event.release.name }}"
          echo "html_url: ${{ github.event.release.html_url }}"
          echo "url: ${{ github.event.release.url }}"
        
