on:
  release:
    types: [released]

jobs:
  show-release-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "name: ${{ github.event.release.name }}"
          echo "tag_name: ${{ github.event.release.tag_name }}"
          echo "html_url: ${{ github.event.release.html_url }}"
          echo "url: ${{ github.event.release.url }}"
          echo "==========================="
          echo "author.login: ${{ github.event.release.author.login }}"
          echo "author.url: ${{ github.event.release.author.url }}"
