on:
  workflow_dispatch:
  
jobs:
  show-multiple-line-text:
    runs-on: ubuntu-latest
    steps:
      - id: create-text
        run: |
          echo "リリース担当者はYOUです。" > temp
          echo "以下の対応をよろしくお願いします！" >> temp
          echo "" >> temp
          echo "• リリースをスキップする場合は、Pre-releaseを削除してください" >> temp
          echo "• リリースに進む場合は、stg環境の更新後にcommitに含まれる関係者と連携して受け入れテストに進んでください" >> temp
          echo "" >> temp
          echo "リリース詳細フロー：<https://www.notion.so/microcms/2024-11-142659cde3ea808e91daceed0d3b4a68?pvs=4>" >> temp
          
      - run: |
          cat temp | sed ':a;N;$!ba;s/\n/\\n/g'
